branch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls", namespace="chat")),
    path("support/", include("support.urls")),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    # path("", views.index, name="index"),
    path("resolve/", views.resolve, name="resolve"),
    path("create/", views.create_chat_request, name="create-chat-request"),
    path("messages/", views.get_all_messages, name="get-all-messages"),
    path("<str:conversation_id>/", views.room, name="room"),
]

support/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("customer/", views.customer_form, name="customer-form"),
    path("customer/<str:email_id>", views.customer, name="customer"),
    path("agent/", views.agent_form, name="agent-form"),
    path("agent/<str:email_id>", views.agent, name="agent"),
]

chat/models.py
from django.db import models
from branch.behaviours import Timestampable, UUIDable
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField, SearchVector


# Create your models here.

class User(Timestampable, UUIDable, models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    name_email_vector = SearchVectorField(null=True, blank=True)
    def __str__(self):
        return self.name
    
    class Meta:
        indexes = [
            GinIndex(
                fields=['name_email_vector'],  # Index on the SearchVectorField
                name='user_name_email_gin'
            ),
        ]
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        User.objects.filter(pk=self.pk).update(name_email_vector=SearchVector('name', 'email'))


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.name

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.user.name

CONVERSATION_STATUS = (
    ('OPEN', 'open'),
    ('ONGOING', 'ongoing'),
    ('RESOLVED', 'resolved'),
)
class Conversation(Timestampable, UUIDable, models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    agent_active = models.BooleanField(default=False)
    status = models.CharField(max_length=20, choices=CONVERSATION_STATUS, default=CONVERSATION_STATUS[0][0])

    def __str__(self):
        return f"{self.customer.user.name} -> {self.status}"
    
class Message(Timestampable, UUIDable, models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_sender')
    text = models.TextField()
    conversation_id = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name="messages")
    is_seen = models.BooleanField(default=False)
    text_vector = SearchVectorField(null=True, blank=True)

    class Meta:
        ordering = ['created_at']
        indexes = [
            GinIndex(
                fields=['text_vector'],  # Index on the SearchVectorField
                name='message_text_gin'
            ),
        ]

    def __str__(self) -> str:
        return f"{self.sender}->{self.conversation_id}->{self.text}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        Message.objects.filter(pk=self.pk).update(text_vector=SearchVector('text'))

chat/views.py
# chat/views.py
from django.shortcuts import render, redirect
from .models import Conversation, CONVERSATION_STATUS, User, Message
import json
from django.http.response import JsonResponse


def index(request):
    return render(request, "chat/index.html")

def room(request, conversation_id):
    is_customer = request.GET.get("is_customer", False)
    conversation_status = Conversation.objects.get(external_id=conversation_id).status
    is_resolved = conversation_status == CONVERSATION_STATUS[2][0]
    return render(request, "chat/room.html", {"conversation_id": conversation_id, "is_customer": is_customer, "is_resolved": is_resolved})

def resolve(request):
    email_id = request.GET.get("email_id")
    conversation_id = request.GET.get("conversation_id")
    Conversation.objects.filter(external_id=conversation_id).update(status=CONVERSATION_STATUS[2][0])
    return redirect("customer", email_id = email_id)

def create_chat_request(request):
    request.POST = json.loads(request.body.decode('utf-8'))
    email_id = request.POST.get("email_id")
    message = request.POST.get("message")
    customer = User.objects.get(email=email_id).customer
    conversation = Conversation.objects.create(customer_id=customer.user.id)
    message = Message.objects.create(sender=customer.user, text=message, conversation_id=conversation)
    return redirect("chat:room", conversation_id=conversation.external_id)

def get_all_messages(request):
    request.POST = json.loads(request.body.decode('utf-8'))
    conversation_id = request.POST.get("conversation_id")
    messages = Conversation.objects.get(external_id=conversation_id).messages.all().values("sender__name", "sender__email", "text", "created_at")
    messages = list(messages)
    for message in messages:
        message["created_at"] = message["created_at"].isoformat()
    return JsonResponse({"messages": messages})

support/views.py
from django.shortcuts import render, redirect
from chat.models import Conversation, Message, Agent, User, Customer, CONVERSATION_STATUS
from django.db.models import Subquery, OuterRef
from django.contrib import messages
from django.contrib.postgres.search import TrigramSimilarity, SearchVector
from django.db.models import F


# Create your views here.

def customer_form(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        user, created = User.objects.get_or_create(name=name, email=email)
        if created:
            Customer.objects.create(user=user)
        return redirect('customer', email_id=email)
    return render(request, "chat/customer_form.html")

def customer(request, email_id):
    first_message_subquery = Message.objects.filter(
        conversation_id=OuterRef('pk')
    ).order_by('created_at')

    open_support_requests = Conversation.objects.filter(customer__user__email=email_id).exclude(status=CONVERSATION_STATUS[2][0]).annotate(
        first_message=Subquery(first_message_subquery.values('text')[:1])
    )

    resolved_support_requests = Conversation.objects.filter(customer__user__email=email_id, status=CONVERSATION_STATUS[2][0]).annotate(
        first_message=Subquery(first_message_subquery.values('text')[:1])
    )

    return render(request, "chat/customer.html", {"email_id": email_id, "resolved_support_requests": resolved_support_requests, "open_support_requests": open_support_requests})

def agent_form(request):
    if request.method == "POST":
        email = request.POST.get('email')
        is_agent_exists = Agent.objects.filter(user__email=email).exists()
        if not is_agent_exists:
            messages.error(request, 'Agent with this email does not exist.')
            return render(request, "chat/agent_form.html")
        return redirect('agent', email_id=email)
    return render(request, "chat/agent_form.html")

def agent(request, email_id):
    search_query = request.GET.get('search', None)

    first_message_subquery = Message.objects.filter(
        conversation_id=OuterRef('pk')
    ).order_by('created_at')
    

    # Available conversations would be those where the agents are inactive
    available_support_requests = Conversation.objects.filter(agent_active=False).exclude(status=CONVERSATION_STATUS[2][0]).annotate(
        first_message=Subquery(first_message_subquery.values('text')[:1])
    )

    if search_query:
        trigram_queryset = available_support_requests.annotate(
            similarity=TrigramSimilarity('messages__text', search_query)
        ).filter(similarity__gt=0.1).order_by('-similarity')

        vector_queryset = available_support_requests.annotate(
            search=SearchVector('customer__user__name_email_vector', 'messages__text_vector')
        ).filter(search=search_query)

        icontains_queryset = available_support_requests.filter(messages__text__icontains=search_query)

        # Combine QuerySets
        combined_queryset = list(vector_queryset) + list(icontains_queryset) + list(trigram_queryset)

        # Remove duplicates if needed
        available_support_requests = list(set(combined_queryset))

    return render(request, "chat/agent.html", {"email_id": email_id, "support_requests": available_support_requests})

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    {% if not is_resolved %}
        {% if not is_customer %}
            <div id="canned-messages-container">
            </div>
        {% endif %}
        <input id="chat-message-input" type="text" size="100"><br>
        <input id="chat-message-submit" type="button" value="Send">
        {% if is_customer %}
            <input id="chat-message-resolve" data-url="{% url 'chat:resolve' %}" type="button" value="Resolve">
        {% endif %}
    {% endif %}
    {{ conversation_id|json_script:"conversation-id" }}
    {{ is_customer|json_script:"is-customer" }}
    <script>
        const conversationId = JSON.parse(document.getElementById('conversation-id').textContent);
        const isCustomer = JSON.parse(document.getElementById('is-customer').textContent) || sessionStorage.getItem('is_customer');

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + conversationId
            + '/'
        );

        chatSocket.onopen = function(e) {
            console.log('Chat socket opened');
            fetchInitialMessages();
        };

        // Function to fetch initial messages
        function fetchInitialMessages() {
            const url = '{% url "chat:get-all-messages" %}'; // Replace with the actual URL
            const headers = new Headers();
            headers.append('Content-Type', 'application/json');
            headers.append('X-CSRFToken', '{{ csrf_token }}');

            const body = JSON.stringify({
                conversation_id: conversationId
            });

            fetch(url, {
                method: 'POST',
                headers: headers,
                body: body
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(messages => {
                const chatLog = document.querySelector('#chat-log');
                messages = messages.messages;
                for(let i=0; i < messages.length; i++){
                    chatLog.value += `${messages[i].sender__name}: ${messages[i].text}\n\n`;
                }
            })
            .catch(error => {
                console.error('Failed to fetch initial messages', error);
            });
        }
    
        chatSocket.onmessage = function(e) {
            const messages = JSON.parse(e.data);
            console.log(messages);
            if (messages.action === "canned_messages") {
                displayCannedMessages(messages.messages);
            }
            console.log(sessionStorage.getItem('is_customer'));
            if (messages.action === "chat_resolved" && sessionStorage.getItem('is_customer') === 'false'){
                var emailId = sessionStorage.getItem("email");
                var fullUrl = "http://localhost:8000/support/agent/" + emailId;
                window.location.href = fullUrl;
            }
            else{
                const chatLog = document.querySelector('#chat-log');
                messages.forEach(message => {
                    chatLog.value += `${message.sender__name}: ${message.text}\n\n`;
                });
            }
        };

        function displayCannedMessages(messages) {
            const container = document.getElementById('canned-messages-container');
            container.innerHTML = '';

            messages.forEach(msg => {
                const button = document.createElement('button');
                button.className = 'canned-message-btn';
                button.textContent = msg;
                button.onclick = () => sendWebSocketMessage(msg);
                container.appendChild(button);
            });
        }

        function sendWebSocketMessage(message) {
            chatSocket.send(JSON.stringify({
                'text': message,
                "action": "chat_message",
                "sender__name": sessionStorage.getItem('name'),
                "sender__email": sessionStorage.getItem('email'),
                "conversation_id": conversationId,
                "is_customer": isCustomer
        }));
}
    
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    
        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };
    
        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'text': message,
                "action": "chat_message",
                "sender__name": sessionStorage.getItem('name'),
                "sender__email": sessionStorage.getItem('email'),
                "conversation_id": conversationId,
                "is_customer": isCustomer
            }));
            messageInputDom.value = '';
        };
        
        document.querySelector('#chat-message-resolve').onclick = function(e){
            // Send resolution message on websockets 
            const resolveMessage = {
                action: "chat_resolved",
                conversation_id: conversationId,
                sender__name: sessionStorage.getItem('name'),
                sender__email: sessionStorage.getItem('email')
            };
            chatSocket.send(JSON.stringify(resolveMessage));
            
            // Redirect to resolve page
            var emailId = sessionStorage.getItem("email");
            var baseUrl = document.getElementById('chat-message-resolve').getAttribute('data-url');
            var fullUrl = baseUrl + '?email_id=' + encodeURIComponent(emailId) + '&conversation_id=' + encodeURIComponent(conversationId);
        
            window.location.href = fullUrl;
        }
        
    </script>    
</body>
</html>

customer/templates/chat/customer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Form</title>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 flex items-center justify-center h-screen w-full">
    <div class="bg-white p-8 rounded-lg shadow-lg w-1/2">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
                <input type="text" id="name" name="name" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
                <input type="email" id="email" name="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
</body>
</html>

support/templates/chat/agent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>Welcome Branch Agent, </title>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <h1 class="text-xl font-bold text-blue-600">Welcome, {{ email_id }}</h1>
        <!-- Search Bar -->
        <div class="mt-4 mb-6">
            <form action="{% url 'agent' email_id %}" method="GET" class="flex">
                <input type="text" name="search" placeholder="Search requests..." class="w-full px-4 py-2 border rounded-l-lg focus:outline-none focus:border-blue-500">
                <button type="submit" class="px-4 text-white bg-blue-500 rounded-r-lg hover:bg-blue-600 focus:outline-none">
                    Search
                </button>
            </form>
        </div>
        
        <h2 class="text-lg font-semibold mt-4">Available Support Requests</h2>
        {% if support_requests %}
            <ul class="list-disc pl-5 mt-2">
                {% for request in support_requests %}
                    <li class="mt-2">
                        <a href="{% url 'chat:room' request.external_id %}" class="block hover:bg-gray-100">
                            <div class="border rounded-lg shadow-sm overflow-hidden">
                                <div class="p-4 bg-white">
                                    <p class="text-gray-700 mb-2"><strong>Date:</strong> {{ request.created_at|date:"Y-m-d H:i" }}</p>
                                    <p class="text-gray-600"><strong>Detail:</strong> {{ request.first_message }}</p>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-gray-600 mt-2">No past support requests found.</p>
        {% endif %}
    </div>
</body>
</html>

support/templates/chat/agent_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Form</title>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 flex items-center justify-center h-screen w-full">
    <div class="bg-white p-8 rounded-lg shadow-lg w-1/2">
        {% if messages %}
            <div class="messages">
            {% for message in messages %}
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                    <strong class="font-bold">Error!</strong>
                    <span class="block sm:inline">{{ message }}</span>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        <h2 class="bg-white text-gray-700 p-2">Agent Support System</h2>
        <form id="agentForm" action="" method="post">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
                <input type="text" id="name" name="name" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
                <input type="email" id="email" name="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
    <script>
        document.getElementById('agentForm').onsubmit = function(event) {
            var email = document.getElementById('email').value;
            var name = document.getElementById('name').value;
            sessionStorage.setItem('email', email);
            sessionStorage.setItem('name', name);
            sessionStorage.setItem('is_customer', false);
        };
    </script>
</body>
</html>

support/templates/chat/customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>Welcome</title>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <h1 class="text-xl font-bold text-blue-600" id="welcome-title">Welcome, </h1>
        
        <form id="support-request-form" class="mt-4">
            <input type="text" id="support-request-text" placeholder="Enter your message" class="border p-2 rounded-lg mr-2 w-1/2">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Create Chat Support Request
            </button>
        </form>
        <h2 class="text-lg font-semibold mt-4">Past Resolved Support Requests</h2>
        {% if resolved_support_requests %}
            <ul class="list-disc pl-5 mt-2">
                {% for request in resolved_support_requests %}
                    <li class="mt-2">
                        <a href="{% url 'chat:room' request.external_id %}?is_customer=True" class="block hover:bg-gray-100">
                            <div class="border rounded-lg shadow-sm overflow-hidden">
                                <div class="p-4 bg-white">
                                    <p class="text-gray-700 mb-2"><strong>Date:</strong> {{ request.created_at|date:"Y-m-d H:i" }}</p>
                                    <p class="text-gray-600"><strong>Detail:</strong> {{ request.first_message }}</p>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-gray-600 mt-2">No past support requests found.</p>
        {% endif %}
        
        <h2 class="text-lg font-semibold mt-4">Ongoing Support Requests</h2>
        {% if open_support_requests %}
            <ul class="list-disc pl-5 mt-2">
                {% for request in open_support_requests %}
                    <li class="mt-2">
                        <a href="{% url 'chat:room' request.external_id %}?is_customer=True" class="block hover:bg-gray-100">
                            <div class="border rounded-lg shadow-sm overflow-hidden">
                                <div class="p-4 bg-white">
                                    <p class="text-gray-700 mb-2"><strong>Date:</strong> {{ request.created_at|date:"Y-m-d H:i" }}</p>
                                    <p class="text-gray-600"><strong>Detail:</strong> {{ request.first_message }}</p>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-gray-600 mt-2">No open support requests found.</p>
        {% endif %}
    </div>
    <script>
        document.getElementById('welcome-title').innerHTML += sessionStorage.getItem('email');

        document.getElementById('support-request-form').addEventListener('submit', function(event) {
            const requestText = document.getElementById('support-request-text').value;
            const emailId = sessionStorage.getItem('email');

            // Define the URL and headers
            const url = '{% url "chat:create-chat-request" %}'; // Replace with your actual URL
            const headers = new Headers();
            headers.append('Content-Type', 'application/json');
            headers.append('X-CSRFToken', '{{ csrf_token }}'); // Replace with your actual CSRF token

            // Create the request body
            const body = JSON.stringify({
                email_id: emailId,
                message: requestText
            });

            // Use fetch to send the POST request
            fetch(url, {
                method: 'POST',
                headers: headers,
                body: body
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                console.log('Request successful with JSON response', data);
            })
            .catch(error => {
                console.error('Request failed', error);
            });
        });


    </script>
</body>
</html>

support/templates/chat/customer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Form</title>
    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 flex items-center justify-center h-screen w-full">
    <div class="bg-white p-8 rounded-lg shadow-lg w-1/2">
        <h2 class="bg-white text-gray-700 p-2">Customer Support System</h2>
        <form id="customerForm" action="" method="post">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
                <input type="text" id="name" name="name" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
                <input type="email" id="email" name="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" required>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
    <script>
        document.getElementById('customerForm').onsubmit = function(event) {
            var email = document.getElementById('email').value;
            var name = document.getElementById('name').value;
            sessionStorage.setItem('email', email);
            sessionStorage.setItem('name', name);
            sessionStorage.setItem('is_customer', true);
        };
    </script>
</body>
</html>